power <- read.delim("household_power_consumption.txt", header = TRUE, sep = ";", dec = ".", colClasses = c("character", "character", "numeric","numeric","numeric", "numeric", "numeric","numeric","numeric"), na.strings = "?")
power2day<- subset(power, (power$Date == "1/2/2007"| power$Date =="2/2/2007"))
power2day$date_time <- paste(power2day$Date, power2day$Time, sep=" ")
power2day$date_time <-as.POSIXct(power2day$date_time, format ="%d/%m/%Y %T")
par(mfrow=c(2,2), mar=c(4,4,4,4))
with(power2day, plot(date_time, Global_reactive_power, type ="l", xlab = "datetime"))
with(power2day, plot(date_time, Voltage, type = "l",xlab = "datetime", ylab = "Voltage"))
with(power2day, plot(date_time, Sub_metering_1, type ="l", xlab = "", ylab = "Energy Sub Metering"))
lines(power2day$date_time, power2day$Sub_metering_2, col = "red" )
lines(power2day$date_time, power2day$Sub_metering_3, col ="blue")
legend("topright", lty=1, lwd=0.5, col=c("black", "red", "blue"), legend = c("Sub_Metering_1", "Sub_Metering_2", "Sub_Metering_3"))
with(power2day, plot(date_time, Global_reactive_power, type ="l", xlab = "datetime"))
dev.copy(png, "Plot4F.png")
dev.off()
savehistory("~/Desktop/CSC Coursera FY18/4.0 Exploratory Data Analysis/ExData_Plotting1/Plot4.R")
